import { describe, expect, it } from "vitest";
import { getExtension, normalizeFile } from "./detect";

describe("detect", () => {
  it("extracts extensions from names and urls", () => {
    expect(getExtension("report.final.DOCX")).toBe("docx");
    expect(getExtension("https://example.com/files/demo.pdf?download=1#page=2")).toBe("pdf");
    expect(getExtension("README")).toBe("");
  });

  it("normalizes ArrayBuffer sources into blobs with inferred mime types", async () => {
    const file = await normalizeFile(new TextEncoder().encode("a,b\n1,2").buffer, "data.tsv");

    expect(file.name).toBe("data.tsv");
    expect(file.extension).toBe("tsv");
    expect(file.mimeType).toBe("text/tab-separated-values");
    expect(file.blob).toBeInstanceOf(Blob);
  });

  it("decodes file names from remote URL sources", async () => {
    const file = await normalizeFile("https://example.com/files/%E5%88%AB%E5%A2%85%E5%9B%BE%E7%BA%B8.dwg?download=1");
    const malformed = await normalizeFile("https://example.com/files/bad%name.dwg");

    expect(file.name).toBe("别墅图纸.dwg");
    expect(file.extension).toBe("dwg");
    expect(malformed.name).toBe("bad%name.dwg");
  });

  it("infers MIME types for common complex preview formats", async () => {
    const docx = await normalizeFile(new ArrayBuffer(1), "letter.docx");
    const docm = await normalizeFile(new ArrayBuffer(1), "macro.docm");
    const zip = await normalizeFile(new ArrayBuffer(1), "bundle.zip");
    const glb = await normalizeFile(new ArrayBuffer(1), "scene.glb");
    const fbx = await normalizeFile(new ArrayBuffer(1), "scene.fbx");
    const ply = await normalizeFile(new ArrayBuffer(1), "scan.ply");
    const drawio = await normalizeFile(new ArrayBuffer(1), "diagram.drawio");
    const topojson = await normalizeFile(new ArrayBuffer(1), "topology.topojson");
    const xlsm = await normalizeFile(new ArrayBuffer(1), "macro.xlsm");
    const xltx = await normalizeFile(new ArrayBuffer(1), "template.xltx");
    const pptm = await normalizeFile(new ArrayBuffer(1), "deck.pptm");
    const potx = await normalizeFile(new ArrayBuffer(1), "deck-template.potx");
    const dxf = await normalizeFile(new ArrayBuffer(1), "drawing.dxf");
    const mkv = await normalizeFile(new ArrayBuffer(1), "movie.mkv");
    const hls = await normalizeFile(new ArrayBuffer(1), "stream.m3u8");
    const ogg = await normalizeFile(new ArrayBuffer(1), "track.ogg");
    const ogv = await normalizeFile(new ArrayBuffer(1), "movie.ogv");
    const apng = await normalizeFile(new ArrayBuffer(1), "animated.apng");
    const heic = await normalizeFile(new ArrayBuffer(1), "photo.heic");
    const heif = await normalizeFile(new ArrayBuffer(1), "photo.heif");
    const jfif = await normalizeFile(new ArrayBuffer(1), "photo.jfif");
    const jpeg2000Future = await normalizeFile(new ArrayBuffer(1), "photo.jxl");
    const cursor = await normalizeFile(new ArrayBuffer(1), "pointer.cur");
    const aiff = await normalizeFile(new ArrayBuffer(1), "recording.aiff");
    const midi = await normalizeFile(new ArrayBuffer(1), "score.midi");
    const caf = await normalizeFile(new ArrayBuffer(1), "recording.caf");
    const mpeg = await normalizeFile(new ArrayBuffer(1), "clip.mpeg");
    const mobileVideo = await normalizeFile(new ArrayBuffer(1), "clip.3g2");
    const m2ts = await normalizeFile(new ArrayBuffer(1), "stream.m2ts");
    const fodt = await normalizeFile(new ArrayBuffer(1), "flat.fodt");
    const fods = await normalizeFile(new ArrayBuffer(1), "flat.fods");
    const fodp = await normalizeFile(new ArrayBuffer(1), "flat.fodp");
    const numbers = await normalizeFile(new ArrayBuffer(1), "sheet.numbers");
    const key = await normalizeFile(new ArrayBuffer(1), "deck.key");
    const usd = await normalizeFile(new ArrayBuffer(1), "scene.usdz");
    const vrml = await normalizeFile(new ArrayBuffer(1), "scene.wrl");
    const ifc = await normalizeFile(new ArrayBuffer(1), "building.ifc");
    const parasolid = await normalizeFile(new ArrayBuffer(1), "part.x_t");
    const rhino = await normalizeFile(new ArrayBuffer(1), "model.3dm");
    const sketchup = await normalizeFile(new ArrayBuffer(1), "model.skp");
    const solidworks = await normalizeFile(new ArrayBuffer(1), "part.sldprt");
    const font = await normalizeFile(new ArrayBuffer(1), "brand.woff2");
    const psd = await normalizeFile(new ArrayBuffer(1), "poster.psd");
    const illustrator = await normalizeFile(new ArrayBuffer(1), "logo.ai");
    const sqlite = await normalizeFile(new ArrayBuffer(1), "cache.sqlite");
    const wasm = await normalizeFile(new ArrayBuffer(1), "module.wasm");
    const parquet = await normalizeFile(new ArrayBuffer(1), "data.parquet");
    const env = await normalizeFile(new ArrayBuffer(1), ".env");
    const gitignore = await normalizeFile(new ArrayBuffer(1), ".gitignore");
    const npmrc = await normalizeFile(new ArrayBuffer(1), ".npmrc");
    const editorconfig = await normalizeFile(new ArrayBuffer(1), ".editorconfig");
    const prettierrc = await normalizeFile(new ArrayBuffer(1), ".prettierrc");
    const properties = await normalizeFile(new ArrayBuffer(1), "app.properties");
    const jsonc = await normalizeFile(new ArrayBuffer(1), "settings.jsonc");
    const json5 = await normalizeFile(new ArrayBuffer(1), "config.json5");
    const notebook = await normalizeFile(new ArrayBuffer(1), "analysis.ipynb");
    const jsonl = await normalizeFile(new ArrayBuffer(1), "events.jsonl");
    const ndjson = await normalizeFile(new ArrayBuffer(1), "events.ndjson");
    const toml = await normalizeFile(new ArrayBuffer(1), "Cargo.toml");
    const protobuf = await normalizeFile(new ArrayBuffer(1), "schema.proto");
    const hcl = await normalizeFile(new ArrayBuffer(1), "main.tf");
    const tfvars = await normalizeFile(new ArrayBuffer(1), "prod.tfvars");
    const latex = await normalizeFile(new ArrayBuffer(1), "paper.tex");
    const bibliography = await normalizeFile(new ArrayBuffer(1), "refs.bib");
    const graphviz = await normalizeFile(new ArrayBuffer(1), "graph.gv");
    const http = await normalizeFile(new ArrayBuffer(1), "request.http");
    const zsh = await normalizeFile(new ArrayBuffer(1), "install.zsh");
    const powershell = await normalizeFile(new ArrayBuffer(1), "install.ps1");
    const batch = await normalizeFile(new ArrayBuffer(1), "install.bat");
    const dockerfile = await normalizeFile(new ArrayBuffer(1), "Dockerfile");
    const css = await normalizeFile(new ArrayBuffer(1), "style.css");
    const ruby = await normalizeFile(new ArrayBuffer(1), "app.rb");
    const swift = await normalizeFile(new ArrayBuffer(1), "View.swift");
    const kotlin = await normalizeFile(new ArrayBuffer(1), "Main.kt");
    const dart = await normalizeFile(new ArrayBuffer(1), "widget.dart");
    const svelte = await normalizeFile(new ArrayBuffer(1), "Component.svelte");
    const elixir = await normalizeFile(new ArrayBuffer(1), "router.ex");
    const graphql = await normalizeFile(new ArrayBuffer(1), "schema.graphql");
    const pem = await normalizeFile(new ArrayBuffer(1), "cert.pem");
    const crt = await normalizeFile(new ArrayBuffer(1), "cert.crt");
    const calendar = await normalizeFile(new ArrayBuffer(1), "event.ics");
    const vcard = await normalizeFile(new ArrayBuffer(1), "contact.vcf");

    expect(docx.mimeType).toBe("application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    expect(docm.mimeType).toBe("application/vnd.ms-word.document.macroenabled.12");
    expect(zip.mimeType).toBe("application/zip");
    expect(glb.mimeType).toBe("model/gltf-binary");
    expect(fbx.mimeType).toBe("application/vnd.autodesk.fbx");
    expect(ply.mimeType).toBe("application/ply");
    expect(drawio.mimeType).toBe("application/vnd.jgraph.mxfile");
    expect(topojson.mimeType).toBe("application/topo+json");
    expect(xlsm.mimeType).toBe("application/vnd.ms-excel.sheet.macroenabled.12");
    expect(xltx.mimeType).toBe("application/vnd.openxmlformats-officedocument.spreadsheetml.template");
    expect(pptm.mimeType).toBe("application/vnd.ms-powerpoint.presentation.macroenabled.12");
    expect(potx.mimeType).toBe("application/vnd.openxmlformats-officedocument.presentationml.template");
    expect(dxf.mimeType).toBe("image/vnd.dxf");
    expect(mkv.mimeType).toBe("video/x-matroska");
    expect(hls.mimeType).toBe("application/vnd.apple.mpegurl");
    expect(ogg.mimeType).toBe("audio/ogg");
    expect(ogv.mimeType).toBe("video/ogg");
    expect(apng.mimeType).toBe("image/apng");
    expect(heic.mimeType).toBe("image/heic");
    expect(heif.mimeType).toBe("image/heif");
    expect(jfif.mimeType).toBe("image/jpeg");
    expect(jpeg2000Future.mimeType).toBe("image/jxl");
    expect(cursor.mimeType).toBe("image/x-icon");
    expect(aiff.mimeType).toBe("audio/aiff");
    expect(midi.mimeType).toBe("audio/midi");
    expect(caf.mimeType).toBe("audio/x-caf");
    expect(mpeg.mimeType).toBe("video/mpeg");
    expect(mobileVideo.mimeType).toBe("video/3gpp2");
    expect(m2ts.mimeType).toBe("video/mp2t");
    expect(fodt.mimeType).toBe("application/vnd.oasis.opendocument.text-flat-xml");
    expect(fods.mimeType).toBe("application/vnd.oasis.opendocument.spreadsheet-flat-xml");
    expect(fodp.mimeType).toBe("application/vnd.oasis.opendocument.presentation-flat-xml");
    expect(numbers.mimeType).toBe("application/vnd.apple.numbers");
    expect(key.mimeType).toBe("application/vnd.apple.keynote");
    expect(usd.mimeType).toBe("model/vnd.usdz+zip");
    expect(vrml.mimeType).toBe("model/vrml");
    expect(ifc.mimeType).toBe("application/x-step");
    expect(parasolid.mimeType).toBe("application/x-parasolid");
    expect(rhino.mimeType).toBe("model/vnd.3dm");
    expect(sketchup.mimeType).toBe("application/vnd.sketchup.skp");
    expect(solidworks.mimeType).toBe("application/sldworks");
    expect(font.mimeType).toBe("font/woff2");
    expect(psd.mimeType).toBe("image/vnd.adobe.photoshop");
    expect(illustrator.mimeType).toBe("application/postscript");
    expect(sqlite.mimeType).toBe("application/vnd.sqlite3");
    expect(wasm.mimeType).toBe("application/wasm");
    expect(parquet.mimeType).toBe("application/vnd.apache.parquet");
    expect(env.mimeType).toBe("text/plain");
    expect(gitignore.mimeType).toBe("text/plain");
    expect(npmrc.mimeType).toBe("text/plain");
    expect(editorconfig.mimeType).toBe("text/plain");
    expect(prettierrc.mimeType).toBe("application/json");
    expect(properties.mimeType).toBe("text/plain");
    expect(jsonc.mimeType).toBe("application/json");
    expect(json5.mimeType).toBe("application/json5");
    expect(notebook.mimeType).toBe("application/x-ipynb+json");
    expect(jsonl.mimeType).toBe("application/x-ndjson");
    expect(ndjson.mimeType).toBe("application/x-ndjson");
    expect(toml.mimeType).toBe("application/toml");
    expect(protobuf.mimeType).toBe("text/x-protobuf");
    expect(hcl.mimeType).toBe("text/x-hcl");
    expect(tfvars.mimeType).toBe("text/x-hcl");
    expect(latex.mimeType).toBe("application/x-tex");
    expect(bibliography.mimeType).toBe("text/x-bibtex");
    expect(graphviz.mimeType).toBe("text/vnd.graphviz");
    expect(http.mimeType).toBe("message/http");
    expect(zsh.mimeType).toBe("application/x-sh");
    expect(powershell.mimeType).toBe("text/plain");
    expect(batch.mimeType).toBe("text/plain");
    expect(dockerfile.mimeType).toBe("");
    expect(css.mimeType).toBe("text/css");
    expect(ruby.mimeType).toBe("text/x-ruby");
    expect(swift.mimeType).toBe("text/x-swift");
    expect(kotlin.mimeType).toBe("text/x-kotlin");
    expect(dart.mimeType).toBe("text/x-dart");
    expect(svelte.mimeType).toBe("text/plain");
    expect(elixir.mimeType).toBe("text/x-elixir");
    expect(graphql.mimeType).toBe("application/graphql");
    expect(pem.mimeType).toBe("application/x-pem-file");
    expect(crt.mimeType).toBe("application/x-x509-ca-cert");
    expect(calendar.mimeType).toBe("text/calendar");
    expect(vcard.mimeType).toBe("text/vcard");
  });
});
